on: push
name: 'Libris Auto-Generate Action'
description: 'Automatically update your documentation on every git push.'
inputs:
  config:
    description: 'The path to the JSON or JavaScript libris config file.'
    required: false
    default: "./docs/libris.json"
  output:
    description: 'The output path for the generated html documentation.'
    required: true
    default: "./docs/index.html"
  branch:
    description: 'The branch where the new edits will be pushed to. Leave "" to use the branch that is being pushed.'
    required: false
    default: "docs"
  orphan:
    description: 'Create an orphan branch when the defined branch does not exist.'
    required: false
    default: "false"
runs:
  using: 'node20'
  main: 'dist/index.js'
